"""Add manual UPI billing, subscriptions and invoices.

Revision ID: 0003_upi_billing
Revises: 0002_web_push
"""
from alembic import op
import sqlalchemy as sa
revision='0003_upi_billing';down_revision='0002_web_push';branch_labels=None;depends_on=None
def upgrade():
    tables=set(sa.inspect(op.get_bind()).get_table_names())
    if 'billing_plans' not in tables:
        op.create_table('billing_plans',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('code',sa.String(40),nullable=False,unique=True),sa.Column('name',sa.String(100),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('amount_paise',sa.Integer(),nullable=False),sa.Column('duration_days',sa.Integer(),nullable=False),sa.Column('grants_role',sa.String(20),nullable=False),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('featured',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_billing_plans_code','billing_plans',['code']);op.create_index('ix_billing_plans_active','billing_plans',['active'])
    if 'payment_requests' not in tables:
        op.create_table('payment_requests',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('plan_id',sa.Integer(),sa.ForeignKey('billing_plans.id',ondelete='RESTRICT'),nullable=False),sa.Column('transaction_reference',sa.String(100),nullable=False,unique=True),sa.Column('amount_paise',sa.Integer(),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('submitted_at',sa.DateTime(timezone=True),nullable=False),sa.Column('reviewed_at',sa.DateTime(timezone=True)),sa.Column('reviewed_by',sa.Integer(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('rejection_reason',sa.Text()));op.create_index('ix_payment_requests_user_id','payment_requests',['user_id']);op.create_index('ix_payment_requests_status','payment_requests',['status']);op.create_index('ix_payment_requests_transaction_reference','payment_requests',['transaction_reference']);op.create_index('ix_payment_requests_submitted_at','payment_requests',['submitted_at'])
    if 'payment_proofs' not in tables:op.create_table('payment_proofs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('payment_id',sa.Integer(),sa.ForeignKey('payment_requests.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('filename',sa.String(160),nullable=False),sa.Column('content_type',sa.String(80),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('size',sa.Integer(),nullable=False),sa.Column('data',sa.LargeBinary(),nullable=False));op.create_index('ix_payment_proofs_payment_id','payment_proofs',['payment_id'])
    if 'subscriptions' not in tables:
        op.create_table('subscriptions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('plan_id',sa.Integer(),sa.ForeignKey('billing_plans.id',ondelete='RESTRICT'),nullable=False),sa.Column('payment_id',sa.Integer(),sa.ForeignKey('payment_requests.id',ondelete='RESTRICT'),nullable=False,unique=True),sa.Column('starts_at',sa.DateTime(timezone=True),nullable=False),sa.Column('ends_at',sa.DateTime(timezone=True),nullable=False),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()));op.create_index('ix_subscriptions_user_id','subscriptions',['user_id']);op.create_index('ix_subscriptions_ends_at','subscriptions',['ends_at']);op.create_index('ix_subscriptions_active','subscriptions',['active'])
    if 'billing_invoices' not in tables:
        op.create_table('billing_invoices',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('invoice_number',sa.String(40),nullable=False,unique=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('payment_id',sa.Integer(),sa.ForeignKey('payment_requests.id',ondelete='RESTRICT'),nullable=False,unique=True),sa.Column('plan_name',sa.String(100),nullable=False),sa.Column('amount_paise',sa.Integer(),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('issued_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_billing_invoices_invoice_number','billing_invoices',['invoice_number']);op.create_index('ix_billing_invoices_user_id','billing_invoices',['user_id']);op.create_index('ix_billing_invoices_issued_at','billing_invoices',['issued_at'])
def downgrade():
    tables=set(sa.inspect(op.get_bind()).get_table_names())
    for table in ('billing_invoices','subscriptions','payment_proofs','payment_requests','billing_plans'):
        if table in tables:op.drop_table(table)
